version: "3.8"

services:
  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - fullstack-net

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8001
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - fullstack-net

networks:
  fullstack-net:
    driver: bridge
